### ISSUE TITLE
It was no working in Xcode 6.1

### ISSUE THREAD

**Issue by vikash1307** [jpsim/DeckRocket#15]
I found some many error in this code.

**Comment by jpsim** [comment]
From the [Requirements](https://github.com/jpsim/DeckRocket#requirements) section of the README:

> Xcode 6.3b2, OS X 10.10 and iOS 8 are all required to build, install and use DeckRocket.

If you'd like to build with Xcode 6.1, please use [0.0.3](https://github.com/jpsim/DeckRocket/releases/tag/0.0.3). Note that there have been bug fixes since that time.
