### ISSUE TITLE
Add Carthage install instructions

### ISSUE THREAD

**Issue by kostiakoval** [jpsim/DeckRocket#21]
Now i need to run `carthage update` to build iOS app (to get Cryptography)

**Comment by lindon-fox** [comment]
For those who have never used Carthage before, you need to follow the installation instructions on this page: https://github.com/Carthage/Carthage and then run `carthage update` in the project directory.

**Comment by jpsim** [comment]
Sorry for the delay in getting back to this, Carthage isn't necessary to build DeckRocket, Carthage is just used to manage git submodules. I've updated the readme in 0ca2f81 to reflect that latest installation instructions.
